db:
  urlPrefix: jdbc:h2:mem:testdb;DB_CLOSE_ON_EXIT=FALSE
  username: sa
  password: password


spring:
  h2:
    console.enabled: true
  datasource:
    password: ${db.password}
    url: ${db.urlPrefix}
    username: ${db.username}
  jpa:
    defer-datasource-initialization: true
    open-in-view: false
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
        format_sql: true
  application:
    name: SqlLockingPractice